spring:
  application:
    name: scamshield-service
  datasource:
    url: jdbc:postgresql://localhost:5432/scamshield
    username: scamshield
    password: scamshield
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

models:
  openai:
    name: gpt-4.1
    api-key: ${OPENAI_API_KEY:my-key}
    endpoint: https://api.openai.com/v1/responses
